development:
  debug: false
  socket_port: 8080
  pubsub_server: 'https://pubsubhubbub.appspot.com/'

test:
  debug: false
  socket_port: 8081
  pubsub_server: 'https://pubsubhubbub.appspot.com/'

production:
  debug: false
  socket_port: 8080
  pubsub_server: 'https://pubsubhubbub.appspot.com/'
