#    Copyright 2010 Diaspora Inc.
#
#    This file is part of Diaspora.
#
#    Diaspora is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Diaspora is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with Diaspora.  If not, see <http://www.gnu.org/licenses/>.
#



cross_server:
  deploy_to: '/usr/local/app/diaspora'
  user: 'root'
  repo: 'git@github.com:diaspora/diaspora.git'
  branch: 'master'
  default_env: 'development'
servers:
  tom:
    - url: 'tom.joindiaspora.com'
  backer:
    - username: 'washington'
      given_name: 'George'
      family_name: 'Washington'
      number: 0
      pin: 5072
    - username: 'adams'
      given_name: 'John'
      family_name: 'Adams'
      number: 1
      pin: 3742
    - username: 'jefferson'
      given_name: 'Thomas'
      family_name: 'Jefferson'
      number: 2
      pin: 7782
    - username: 'madison'
      given_name: 'James'
      family_name: 'Madison'
      number: 3
      pin: 2691
    - username: 'monroe'
      given_name: 'James'
      family_name: 'Monroe'
      number: 4
      pin: 6133
    - username: 'quincyadams'
      given_name: 'John Quincy'
      family_name: 'Adams'
      number: 5
      pin: 7558
    - username: 'jackson'
      given_name: 'Andrew'
      family_name: 'Jackson'
      number: 6
      pin: 8670
    - username: 'buren'
      given_name: 'Martin'
      family_name: 'Van Buren'
      number: 7
      pin: 1559
    - username: 'harrison'
      given_name: 'William Henry'
      family_name: 'Harrison'
      number: 8
      pin: 5404
    - username: 'tyler'
      given_name: 'John'
      family_name: 'Tyler'
      number: 9
      pin: 6431
    - username: 'polk'
      given_name: 'James K.'
      family_name: 'Polk'
      number: 10
      pin: 1957
