default: 'en'
available:
  cs: 'Lietuviškai'
  cy: 'Cymraeg'
  de: 'Deutsch'
  en: 'English'
  es: 'Español'
  fr: 'Français'
  id: 'Bahasa Indonesia'
  it: 'Italiano'
  nb: 'Norske'
  nl: 'Nederlands'
  pt-BR: 'Português'
  ro: 'Română'
  ru: 'Россию'
  sv: 'Svenska'
  tr: 'Türk'
