defaults: &defaults
  host: localhost
  allow_dynamic_fields: false
  parameterize_keys: true
  persist_in_safe_mode: true
  raise_not_found_error: false
  reconnect_time: 3
  use_object_ids: false
  

development:
  <<: *defaults
  database: diaspora_development

test:
  <<: *defaults
  database: diaspora_test

# set these environment variables on your prod server
production:
  <<: *defaults
  #host: <%= ENV['MONGOID_HOST'] %>
  #port: <%= ENV['MONGOID_PORT'] %>
  #username: <%= ENV['MONGOID_USERNAME'] %>
  #password: <%= ENV['MONGOID_PASSWORD'] %>
  #database: <%= ENV['MONGOID_DATABASE'] %>
