#    Copyright 2010 Diaspora Inc.
#
#    This file is part of Diaspora.
#
#    Diaspora is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Diaspora is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with Diaspora.  If not, see <http://www.gnu.org/licenses/>.
#



rackup: /usr/local/app/diaspora/current/config.ru
pid: /tmp/pids/thin.pid
wait: 30
timeout: 600
log: /usr/local/log/thin
max_conns: 1024
require: []

max_persistent_conns: 512
environment: development 
servers: 1
daemonize: true
#chdir: /usr/applications/localhash/current
#socket: /tmp/thin.sock
port: 80
