#rackup: /opt/applications/localhash/current/config.ru
#pid: /tmp/pids/thin.pid
wait: 30
timeout: 600
#log: /var/log/thin
#max_conns: 1024
#require: []

#max_persistent_conns: 512
environment: production
#servers: 4
daemonize: true
#chdir: /usr/applications/localhash/current
socket: /tmp/thin.sock

